# Generated by Django 4.0.4 on 2022-05-20 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payer',
            new_name='Payment',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='payer',
            new_name='payment',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='payer',
            new_name='payment',
        ),
        migrations.RemoveField(
            model_name='tourguide',
            name='department',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
