# Generated by Django 4.0.4 on 2022-05-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_rename_payer_payment_rename_payer_customer_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artical',
            name='image',
            field=models.ImageField(default=None, upload_to='images/artical/%Y/%m'),
        ),
    ]
