# Generated by Django 4.0.4 on 2022-05-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0003_alter_artical_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='active',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='address',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='name_hotel',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='updated_date',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='active',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='address',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='email',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='name_transport',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='seat',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='updated_date',
        ),
        migrations.AddField(
            model_name='hotel',
            name='name',
            field=models.CharField(default='SOME STRING', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='name',
            field=models.CharField(default='SOME STRING', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='hotels',
            field=models.ManyToManyField(blank=True, null=True, related_name='tours', to='travelapp.hotel'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='transports',
            field=models.ManyToManyField(blank=True, null=True, related_name='tours', to='travelapp.transport'),
        ),
    ]
