# Generated by Django 4.0.4 on 2022-05-20 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0004_remove_hotel_active_remove_hotel_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='country',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='hotels',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='service',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='transports',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Hotel',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='Transport',
        ),
    ]
