# Generated by Django 4.0.4 on 2022-05-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0005_remove_tour_country_remove_tour_hotels_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artical',
            name='image',
            field=models.ImageField(null=True, upload_to='images/artical/%Y/%m'),
        ),
    ]
