# Generated by Django 4.0.4 on 2022-05-21 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0007_comment_active_alter_comment_artical_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payment',
            new_name='Payer',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='payment',
            new_name='payer',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='payment',
            new_name='payer',
        ),
    ]
